# https://github.com/MagilaWEB/unblock-youtube-discord
# https://github.com/ankddev/zapret-discord-youtube
import os

BIN_FOLDER, LISTS_FOLDER, APP_VERSION = "bin", "lists", "14.9.9"

WINWS_EXE = os.path.join(BIN_FOLDER, "winws.exe")
ICON_PATH = os.path.join(BIN_FOLDER, "zapret.ico")

# Настройки для GitHub стратегий
GITHUB_STRATEGIES_BASE_URL = "https://gitflic.ru/project/main1234/main1234/blob/raw?file="
GITHUB_STRATEGIES_JSON_URL = "https://gitflic.ru/project/main1234/main1234/blob/raw?file=index.json"
STRATEGIES_FOLDER = BIN_FOLDER

# Discord TCP конфигурации

#DiscordFix (ALT v10).bat
Ankddev10_1 = ""


#$UDP6 = "--filter-udp=50000-65535 --dpi-desync=fake,split2 --dpi-desync-any-protocol --dpi-desync-cutoff=d2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_test_00.bin --new"


DPI_COMMANDS = {

Ultimate Fix ALT Beeline-Rostelekom
--wf-tcp=80,443 --wf-udp=443,50000-65535
--filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_vk_com.bin --new
--filter-udp=50000-65535 --ipset={LISTS_FOLDER}/ipset-discord.txt --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --new
--filter-tcp=80 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake,split2 --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-repeats=6 --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_sberbank_ru.bin --new
--filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-repeats=2 --dpi-desync-cutoff=n2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_test_00.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtubeGV.txt --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-cutoff=d2 --dpi-desync-ttl=4 --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=2 --dpi-desync-split-pos=3 --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new

split с sniext
--wf-tcp=80,443 --wf-udp=443,50000-59000
--filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-repeats=4 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/youtubeGV.txt --dpi-desync=multisplit --dpi-desync-split-seqovl=1 --dpi-desync-split-pos=midsld-1 --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=split --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_www_google_com.bin --dpi-desync-ttl=1 --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=syndata --dpi-desync-fake-syndata={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=5 --new
--filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=7 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new
--filter-udp=50000-59000 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=n2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new

split с badseq
--wf-tcp=80,443 --wf-udp=443,50000-59000
--filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-repeats=4 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/youtubeGV.txt --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-cutoff=d2 --dpi-desync-ttl=4 --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-autottl=2 --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=syndata --dpi-desync-fake-syndata={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=5 --new
--filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=7 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new
--filter-udp=50000-59000 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=n2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new
--filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new

"Ростелеком и Мегафон":  f"--wf-tcp=80,443 --wf-udp=443,50000-59000 --filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-repeats=4 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-autottl=2 --new --filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-udp=50000-59000 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake,split --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_www_google_com.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern={BIN_FOLDER}/tls_clienthello_4.bin --new",
"Ростелеком и МГТС":  f"--wf-tcp=80,443 --wf-udp=443,50000-59000 --filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-repeats=4 --dpi-desync-fake-quic={BIN_FOLDER}/quic_1.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=2 --dpi-desync-split-pos=3 --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_2.bin --dpi-desync-autottl=2 --new --filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-udp=50000-59000 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake,split --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_www_google_com.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern={BIN_FOLDER}/tls_clienthello_4.bin --new",
"Другие провайдеры v1": f"--wf-l3=ipv4,ipv6 --wf-tcp=443 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=split --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_www_google_com.bin --dpi-desync-ttl=1 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_4.bin --dpi-desync-ttl=4 --new --filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake,split2 --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic={BIN_FOLDER}\quic_initial_www_google_com.bin --new --filter-udp=50000-59000 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern={BIN_FOLDER}/tls_clienthello_4.bin --new",

"Другие провайдеры v2": f"--wf-l3=ipv4,ipv6 --wf-tcp=443 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_www_google_com.bin --dpi-desync-ttl=4 --new --filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic={BIN_FOLDER}\quic_initial_www_google_com.bin --new --filter-udp=50000-59000 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-cutoff=n5 --dpi-desync-repeats=10 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_www_google_com.bin --dpi-desync-ttl=2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern={BIN_FOLDER}/tls_clienthello_4.bin --new",

"Ankddev v10": f"--wf-l3=ipv4,ipv6 --wf-tcp=443 --wf-udp=443,50000-65535 --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=syndata,disorder2 --dpi-desync-split-pos=3 --dpi-desync-repeats=11 --dpi-desync-fooling=badseq --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_www_google_com.bin --new --filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake,split2 --dpi-desync-repeats=11 --dpi-desync-udplen-increment=15 --dpi-desync-fake-quic={BIN_FOLDER}\quic_initial_www_google_com.bin --new --filter-udp=50000-50099 --ipset={LISTS_FOLDER}/ipset-discord.txt --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-cutoff=d5 --dpi-desync-repeats=11 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=syndata,multidisorder2 --dpi-desync-split-pos=4 --dpi-desync-repeats=10 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_vk_com_kyber.bin --new --filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake,split2 --dpi-desync-repeats=10 --dpi-desync-udplen-increment=25 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new",

"МГТС v1":  f"--wf-tcp=80,443 --wf-udp=443,50000-50010 --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtubeGV.txt --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-cutoff=d2 --dpi-desync-ttl=4 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=split --dpi-desync-split-pos=3 --dpi-desync-repeats=4 --dpi-desync-autottl=1 --new --filter-udp=50000-50010 --ipset={LISTS_FOLDER}/ipset-discord.txt --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-autottl --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern={BIN_FOLDER}/tls_clienthello_4.bin --new",
"МГТС v2":  f"--wf-tcp=80,443 --wf-udp=443,50000-50900 --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-cutoff=d2 --dpi-desync-ttl=3 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-ttl=3 --new --filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-repeats=2 --dpi-desync-cutoff=n2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=7 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic={BIN_FOLDER}/quic_test_00.bin --dpi-desync-cutoff=n2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern={BIN_FOLDER}/tls_clienthello_4.bin --new",
"МГТС v3":  f"--wf-tcp=80,443 --wf-udp=443,50000-50900 --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=split --dpi-desync-split-pos=3 --dpi-desync-repeats=4 --dpi-desync-autottl=1 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-ttl=3 --new --filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-repeats=2 --dpi-desync-cutoff=n2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_initial_www_google_com.bin --new --filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=7 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic={BIN_FOLDER}/quic_test_00.bin --dpi-desync-cutoff=n2 --new --filter-udp=50000-59000 --dpi-desync=fake,split2 --dpi-desync-any-protocol --dpi-desync-cutoff=d2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_test_00.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern={BIN_FOLDER}/tls_clienthello_4.bin --new",
"МГТС v4":  f"--wf-tcp=80,443 --wf-udp=443,50000-50900 --filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-repeats=2 --dpi-desync-cutoff=n2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_test_00.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtubeGV.txt --dpi-desync=multisplit --dpi-desync-split-seqovl=1 --dpi-desync-split-pos=midsld-1 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=2 --dpi-desync-split-pos=3 --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_www_google_com.bin --dpi-desync-ttl=3 --new --filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=7 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic={BIN_FOLDER}/quic_test_00.bin --dpi-desync-cutoff=n2 --new --filter-udp=50000-59000 --dpi-desync=fake,split2 --dpi-desync-any-protocol --dpi-desync-cutoff=d2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_test_00.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-ttl=4 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sniext --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-ttl=2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern={BIN_FOLDER}/tls_clienthello_4.bin --new",
"Ultimate Config ZL":  f"--wf-tcp=80,443 --wf-udp=443,50000-50099 --filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake --dpi-desync-fake-quic={BIN_FOLDER}/quic_1.bin --dpi-desync-repeats=4 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtubeGV.txt --dpi-desync=fakedsplit --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-ttl=4 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtube.txt --dpi-desync=fake,multisplit --dpi-desync-split-seqovl=2 --dpi-desync-split-pos=3 --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_2.bin --dpi-desync-ttl=3 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fakedsplit --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-autottl --new --filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic={BIN_FOLDER}\quic_2.bin --dpi-desync-repeats=8 --dpi-desync-cutoff=n2 --new --filter-udp=50000-50099 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_1.bin --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,multisplit --dpi-desync-split-seqovl=1 --dpi-desync-split-pos=1 --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_vk_com.bin --dpi-desync-ttl=5 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern={BIN_FOLDER}/tls_clienthello_4.bin --new",
"Ultimate Config v2":  f"--wf-tcp=80,443 --wf-udp=443,50000-50090 --filter-tcp=443 --ipset={LISTS_FOLDER}/russia-youtube-rtmps.txt --dpi-desync=syndata --dpi-desync-fake-syndata={BIN_FOLDER}/tls_clienthello_4.bin --dpi-desync-autottl --new --filter-udp=443 --hostlist={LISTS_FOLDER}/youtubeQ.txt --dpi-desync=fake,udplen --dpi-desync-udplen-increment=2 --dpi-desync-fake-quic={BIN_FOLDER}/quic_3.bin --dpi-desync-cutoff=n3 --dpi-desync-repeats=2 --new --filter-tcp=443 --ipset={LISTS_FOLDER}/ipset-discord.txt --dpi-desync=syndata --dpi-desync-fake-syndata={BIN_FOLDER}/tls_clienthello_3.bin --dpi-desync-autottl --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=multisplit --dpi-desync-split-seqovl=1 --dpi-desync-split-pos=midsld+1 --new --filter-udp=443 --hostlist={LISTS_FOLDER}/discord.txt --dpi-desync=fake,udplen --dpi-desync-udplen-increment=5 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic={BIN_FOLDER}\quic_2.bin --dpi-desync-repeats=7 --dpi-desync-cutoff=n2 --new --filter-udp=50000-50090 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=n3 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/youtubeGV.txt --dpi-desync=multisplit --dpi-desync-split-seqovl=1 --dpi-desync-split-pos=midsld-1 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,multisplit --dpi-desync-fooling=md5sig --dpi-desync-autottl --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/other.txt --dpi-desync=fake,multisplit --dpi-desync-split-seqovl=1 --dpi-desync-split-pos=midsld-1 --dpi-desync-fooling=md5sig,badseq --dpi-desync-fake-tls={BIN_FOLDER}/tls_clienthello_4.bin --dpi-desync-ttl=2 --new --filter-tcp=443 --hostlist={LISTS_FOLDER}/faceinsta.txt --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern={BIN_FOLDER}/tls_clienthello_4.bin --new"
}