#!/usr/bin/env python
"""
write_build_info.py <stable|test> <version>

Примеры:
    python build_tools/write_build_info.py stable 16.2.0.0
    python build_tools/write_build_info.py test   16.2.0.100
"""
from __future__ import annotations
import sys, pathlib, datetime, textwrap

def main():
    if len(sys.argv) != 3:
        sys.exit(textwrap.dedent("""
            usage:
                python write_build_info.py <stable|test> <version>
            """))
    channel, version = sys.argv[1:3]
    if channel not in ("stable", "test"):
        sys.exit("channel must be 'stable' or 'test'")

    dst = pathlib.Path("config") / "build_info.py"
    dst.parent.mkdir(exist_ok=True)
    dst.write_text(
        "# AUTOGENERATED {}\n"
        "CHANNEL = {!r}\n"
        "APP_VERSION = {!r}\n".format(
            datetime.datetime.utcnow().isoformat(timespec="seconds"),
            channel,
            version
        ),
        encoding="utf-8"
    )
    print("✔ build_info.py written:", dst)

if __name__ == "__main__":
    main()
