#!/usr/bin/env python
"""
write_build_info.py <stable|test> <version>

Примеры:
    python build_tools/write_build_info.py stable 16.2.0.0
    python build_tools/write_build_info.py test   16.2.0.100
"""
from __future__ import annotations
import datetime
import pathlib
import sys
import textwrap


def write_build_info(channel: str, version: str) -> pathlib.Path:
    if channel not in ("stable", "test"):
        raise ValueError("channel must be 'stable' or 'test'")

    root = pathlib.Path(__file__).resolve().parents[1]
    dst = root / "config" / "build_info.py"
    dst.parent.mkdir(exist_ok=True)
    dst.write_text(
        "# AUTOGENERATED {}\n"
        "CHANNEL = {!r}\n"
        "APP_VERSION = {!r}\n".format(
            datetime.datetime.utcnow().isoformat(timespec="seconds"),
            channel,
            version,
        ),
        encoding="utf-8-sig",
    )
    return dst

def main():
    if len(sys.argv) != 3:
        sys.exit(textwrap.dedent("""
            usage:
                python write_build_info.py <stable|test> <version>
            """))
    channel, version = sys.argv[1:3]
    try:
        dst = write_build_info(channel, version)
    except ValueError as e:
        sys.exit(str(e))
    print("✔ build_info.py written:", dst)

if __name__ == "__main__":
    main()
